using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PauseMenu : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        GetComponent<Canvas>().enabled = false;
    }

    // Update is called once per frame
    void Update()
    {
        //IF the escape key is pressed
        if(Input.GetKeyDown(KeyCode.Escape) && Time.timeScale == 1)
        {
            Debug.Log("Game Paused");
            //display the pause menu
            GetComponent<Canvas>().enabled = true;
            //pause the game
            Time.timeScale = 0;
        }
        else if(Input.GetKeyDown(KeyCode.Escape) && Time.timeScale == 0)
        {
            Resume();

            Debug.Log("Game Unpaused");
        }
    }
    public void Resume() 
    {
        //hide the pause canvas again
        GetComponent<Canvas>().enabled = false;
        //reset the time scale to 1
        Time.timeScale = 1;
    }

    public void ReloadLevel()
    {
        Debug.Log("Level Reloaded");
        Time.timeScale = 1;
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }

    public void QuitGame()

    {
        Debug.Log("Quit Game");
        Application.Quit();
    }

}
